#version: '3.4'

#services:
#  project:
#    image: ${DOCKER_REGISTRY-}project
#    build:
#      context: .
#      dockerfile: Project/Dockerfile


version: "3.9"

services:
    web:
       # image: ${DOCKER_REGISTRY-}project
        build: 
            context: .
            dockerfile: Project/Dockerfile
        ports:
           - "8000:80"
        depends_on:
           - db
           - redis
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
    redis:
        restart: always
        image: redis:latest
        ports:
            - "6379:6379"